# .github/labeler.yml

'area:testing':
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'
          - '**/*_test.py'
          - '**/test_*.py'

'area:documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '**/*.md'

'area:ci-cd':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

'area:firmware-core':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'
          - 'firmware/**'
