target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "I"]
ignore = []

[lint.per-file-ignores]
"tests/*" = ["E402", "PLR2004", "S101", "D"]

[format]
quote-style = "double"
indent-style = "space"
