// ==============================================================================
// ARCHITECTURE : PHANTOM GRID / TOP-TIER INDUSTRIAL PDF SPECIFICATION
// MODULE       : generated_tables.typ
// SIGNED BY    : Commander Jack (👑 霸丸總指揮官權威落款)
// SEAL TIME    : 2026-10-02 13:47:24 CST
// STATUS       : OFFICIALLY RELEASED & SEALED
// INTEGRITY    : SHA256:0892c695ce67f35f... [VERIFIED]
// SPEC STANDARD: PG-SPEC-2026-PDF-WORLD-CLASS
// ==============================================================================

// AUTO-GENERATED BY compile_matrix.py - DO NOT EDIT MANUALLY
// PHANTOM GRID Automotive Toolchain

#let auto-timing-table = table(
  columns: (1.5fr, 1.2fr, 2.5fr, 1.2fr),
  align: (left, center, left, center),
  stroke: (x, y) => if y == 0 { (bottom: 1.2pt + rgb("#0F172A")) } else { (bottom: 0.3pt + rgb("#E2E8F0")) },
  fill: (x, y) => if y == 0 { rgb("#F1F5F9") } else { none },
  table.header([*暫存器*], [*硬體值*], [*計算依據 / 位元域*], [*採樣點 / 狀態*]),
  [BRGCON1], [`0x40`], [SJW=2 Tq, BRP=0 (16MHz 晶振)], [500 kbps],
  [BRGCON2], [`0xC1`], [SAM=3次取樣, Phase1=5 Tq, Prop=2 Tq], [75%],
  [BRGCON3], [`0x03`], [Phase2=4 Tq (總 Tq = 16)], [PASS]
)
