// =============================================================================
// Embodied AI Neuro-Symbolic Fast-Loop Safety Guard - C-ABI Compatible Types
// Zero-Heap Allocation, Deterministic #[repr(C)] Data Structures
// =============================================================================

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GuardStatus {
    Normal = 0,
    Intervention = 1,
    EmergencyBraking = 2,
    SensorFault = 3,
}

impl Default for GuardStatus {
    fn default() -> Self {
        GuardStatus::Normal
    }
}

/// Dynamic joint telemetry from robot hardware / fast sensor loop
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct JointState {
    pub q: [f32; 6],
    pub qd: [f32; 6],
    pub tau_est: [f32; 6],
    pub timestamp_us: u64,
}

/// Unverified candidate action generated by asynchronous slow loop (NPU/Policy)
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct CandidateAction {
    pub q_des: [f32; 6],
    pub qd_des: [f32; 6],
    pub tau_ff: [f32; 6],
    pub kp: [f32; 6],
    pub kd: [f32; 6],
    pub seq_id: u64,
    pub timestamp_us: u64,
}

/// Formally verified, forward-invariant actuator commands dispatched to motors
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
pub struct VerifiedActuatorCommand {
    pub tau_cmd: [f32; 6],
    pub is_intervention: bool,
    pub violation_mask: u32,
    pub execution_time_us: f32,
    pub status: GuardStatus,
}

/// Hard physical and kinematic safety invariants
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PhysicalSafetyBounds {
    pub q_min: [f32; 6],
    pub q_max: [f32; 6],
    pub qd_max: [f32; 6],
    pub tau_max: [f32; 6],
    pub gamma: f32,
    pub damping_kd: [f32; 6],
}

impl Default for PhysicalSafetyBounds {
    fn default() -> Self {
        Self {
            q_min: [-2.8, -1.8, -2.5, -2.8, -1.8, -2.8],
            q_max: [ 2.8,  1.8,  2.5,  2.8,  1.8,  2.8],
            qd_max: [3.14, 3.14, 3.14, 4.0, 4.0, 4.0],
            tau_max: [80.0, 80.0, 60.0, 40.0, 30.0, 30.0],
            gamma: 12.0,
            damping_kd: [5.0, 5.0, 5.0, 3.0, 3.0, 3.0],
        }
    }
}
