"""
==============================================================================
 ARCHITECTURE : PHANTOM GRID / TOP-TIER INDUSTRIAL PDF SPECIFICATION
 MODULE       : compile_matrix.py
 SIGNED BY    : Commander Jack (👑 霸丸總指揮官權威落款)
 SEAL TIME    : 2026-10-02 13:47:24 CST
 STATUS       : OFFICIALLY RELEASED & SEALED
 INTEGRITY    : SHA256:b81b62f8d433333c... [VERIFIED]
 SPEC STANDARD: PG-SPEC-2026-PDF-WORLD-CLASS
==============================================================================
"""

import os
import sys
from pathlib import Path

# 強制 UTF-8 輸出
if sys.platform.startswith("win"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

BASE_DIR = Path(__file__).resolve().parent.parent
GENERATED_FILE = BASE_DIR / "docs" / "generated_tables.typ"

def calculate_pic_timing(f_osc_mhz=16, target_baud_kbps=500, sjw_tq=2, sample_point_pct=75):
    """
    精確計算 Microchip PIC18F25K80 CAN 鮑率暫存器 (BRGCON1/2/3)
    公式: Nominal Bit Time = Sync_Seg(1) + Prop_Seg + Phase_Seg1 + Phase_Seg2
    """
    total_tq = 16  # 標準 16 Tq 採樣模型
    brp = int(f_osc_mhz * 1_000_000 / (2 * total_tq * target_baud_kbps * 1000)) - 1
    
    # 根據取樣點反推 Phase Segments
    sample_tq = int(total_tq * (sample_point_pct / 100.0))
    sync_seg = 1
    prop_seg = 2
    phase_seg1 = sample_tq - sync_seg - prop_seg
    phase_seg2 = total_tq - sync_seg - prop_seg - phase_seg1
    
    brgcon1 = f"0x{(sjw_tq - 1) << 6 | (brp & 0x3F):02X}"
    brgcon2 = f"0x{0x80 | ((phase_seg1 - 1) << 3) | (prop_seg - 1):02X}"  # SAM=1
    brgcon3 = f"0x{phase_seg2 - 1:02X}"
    
    return {
        "baud": f"{target_baud_kbps} kbps",
        "brp": brp,
        "brgcon1": brgcon1,
        "brgcon2": brgcon2,
        "brgcon3": brgcon3,
        "actual_sample": f"{sample_point_pct}%"
    }

def generate_typst_tables():
    timing = calculate_pic_timing(16, 500, sjw_tq=2, sample_point_pct=75)
    GENERATED_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    content = f"""// AUTO-GENERATED BY compile_matrix.py - DO NOT EDIT MANUALLY
// PHANTOM GRID Automotive Toolchain

#let auto-timing-table = table(
  columns: (1.5fr, 1.2fr, 2.5fr, 1.2fr),
  align: (left, center, left, center),
  stroke: (x, y) => if y == 0 {{ (bottom: 1.2pt + rgb("#0F172A")) }} else {{ (bottom: 0.3pt + rgb("#E2E8F0")) }},
  fill: (x, y) => if y == 0 {{ rgb("#F1F5F9") }} else {{ none }},
  table.header([*暫存器*], [*硬體值*], [*計算依據 / 位元域*], [*採樣點 / 狀態*]),
  [BRGCON1], [`{timing['brgcon1']}`], [SJW=2 Tq, BRP={timing['brp']} (16MHz 晶振)], [500 kbps],
  [BRGCON2], [`{timing['brgcon2']}`], [SAM=3次取樣, Phase1=5 Tq, Prop=2 Tq], [{timing['actual_sample']}],
  [BRGCON3], [`{timing['brgcon3']}`], [Phase2=4 Tq (總 Tq = 16)], [PASS]
)
"""
    GENERATED_FILE.write_text(content, encoding="utf-8")
    print(f"✅ [Data-Driven] 已自動算定位元時序並生成: {GENERATED_FILE}")

if __name__ == "__main__":
    generate_typst_tables()
