# -*- coding: utf-8 -*-
"""
PROJ-EXAM-14 AutoCAD DXF A3 Lighting Control & Derating Architecture
Generated by 🛠️ A02 小開 (Agent_Coder)
"""
from __future__ import annotations
import os
import sys
import ezdxf
from ezdxf import colors

# Windows UTF-8 encoding guard
if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
if sys.stderr.encoding != 'utf-8':
    sys.stderr.reconfigure(encoding='utf-8')

def sanitize_cell(value: str) -> str:
    """CWE-1236: CSV/Spreadsheet Injection Prevention (also useful for basic text sanitization)"""
    if not value:
        return ""
    value = str(value)
    if value and value[0] in ('=', '+', '-', '@', '\t', '\r'):
        return "'" + value
    return value

def generate_lighting_derating_a3_dxf(output_path: str):
    """
    Generates an A3 landscape (420x297mm) DXF drawing with the full lighting control,
    derating compensation & overcurrent protection architecture.
    """
    doc = ezdxf.new('R2010')
    doc.header['$MEASUREMENT'] = 1  # Metric
    doc.header['$INSUNITS'] = 4     # Millimeters
    msp = doc.modelspace()
    
    # Define Layers
    doc.layers.add("ELEC_POWER", color=colors.RED)       # ACI 1
    doc.layers.add("ELEC_GND", color=colors.GREEN)       # ACI 3
    doc.layers.add("ELEC_SIG", color=colors.BLUE)        # ACI 5
    doc.layers.add("SAFE_STATE_MACH", color=colors.YELLOW) # ACI 2
    doc.layers.add("SAFE_DEGRADE", color=colors.MAGENTA) # ACI 6
    doc.layers.add("SAFE_FTTI", color=colors.CYAN)       # ACI 4
    doc.layers.add("SAFE_OC", color=30)                  # ACI 30 Orange
    doc.layers.add("FRAME", color=colors.WHITE)          # Default frame
    doc.layers.add("TEXT", color=colors.WHITE)

    # 1. ISO 5457 A3 Border (420x297), 10mm margins
    # Frame coordinates: (10,10) to (410,287)
    msp.add_lwpolyline([(10, 10), (410, 10), (410, 287), (10, 287), (10, 10)], 
                       dxfattribs={'layer': 'FRAME'})

    # Title Block at bottom-right: (310, 10) to (410, 40)
    msp.add_lwpolyline([(310, 10), (310, 40), (410, 40), (410, 10)], 
                       dxfattribs={'layer': 'FRAME'})
    msp.add_line((310, 30), (410, 30), dxfattribs={'layer': 'FRAME'})
    msp.add_line((310, 20), (410, 20), dxfattribs={'layer': 'FRAME'})
    
    # Clean texts
    title = sanitize_cell("PROJ-EXAM-14 Lighting Control & Derating Architecture")
    date_str = sanitize_cell("Date: 2026-08-27")
    author_str = sanitize_cell("Five-Agent AI OS - A02 小開 (Agent_Coder)")

    msp.add_text(title, dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((312, 33))
    msp.add_text(date_str, dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((312, 23))
    msp.add_text(author_str, dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((312, 13))

    # 2. Left zone: Battery 12V -> Main Fuse 30A -> PROFET
    # ELEC_POWER
    msp.add_text("Battery 12V", dxfattribs={'layer': 'TEXT', 'height': 3}).set_placement((20, 250))
    msp.add_lwpolyline([(30, 245), (30, 220), (50, 220)], dxfattribs={'layer': 'ELEC_POWER'})
    
    # Fuse Box
    msp.add_lwpolyline([(50, 215), (70, 215), (70, 225), (50, 225), (50, 215)], dxfattribs={'layer': 'ELEC_POWER'})
    msp.add_text("Fuse 30A", dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((52, 218))
    
    # Power to PROFET
    msp.add_lwpolyline([(70, 220), (90, 220)], dxfattribs={'layer': 'ELEC_POWER'})
    
    # PROFET Array
    msp.add_lwpolyline([(90, 150), (130, 150), (130, 260), (90, 260), (90, 150)], dxfattribs={'layer': 'ELEC_POWER'})
    msp.add_text("PROFET BTS7008\nHigh-Side Switch\n(8 Channels)", 
                 dxfattribs={'layer': 'TEXT', 'height': 3}).set_placement((95, 205))
    
    # GND
    msp.add_lwpolyline([(110, 150), (110, 140), (120, 140)], dxfattribs={'layer': 'ELEC_GND'})
    msp.add_text("GND", dxfattribs={'layer': 'TEXT', 'height': 3}).set_placement((122, 138))

    # 3. Center zone: State machine diagram
    sm_center_x, sm_center_y = 200, 200
    states = [
        ("INIT", sm_center_x, sm_center_y + 40),
        ("NORMAL", sm_center_x + 40, sm_center_y + 10),
        ("DERATING", sm_center_x + 30, sm_center_y - 40),
        ("OVERCURRENT", sm_center_x - 30, sm_center_y - 40),
        ("SAFE_STATE", sm_center_x - 40, sm_center_y + 10)
    ]
    
    for name, x, y in states:
        msp.add_circle((x, y), 10, dxfattribs={'layer': 'SAFE_STATE_MACH'})
        msp.add_text(name, dxfattribs={'layer': 'TEXT', 'height': 2}).set_placement((x-7, y-1))
        
    # Transitions (simplified orthogonal lines where possible, or straight lines)
    msp.add_line((sm_center_x, sm_center_y + 30), (sm_center_x + 30, sm_center_y + 15), dxfattribs={'layer': 'SAFE_STATE_MACH'})
    msp.add_line((sm_center_x + 40, sm_center_y), (sm_center_x + 35, sm_center_y - 30), dxfattribs={'layer': 'SAFE_STATE_MACH'})
    msp.add_line((sm_center_x + 20, sm_center_y - 40), (sm_center_x - 20, sm_center_y - 40), dxfattribs={'layer': 'SAFE_STATE_MACH'})
    msp.add_line((sm_center_x - 40, sm_center_y), (sm_center_x - 35, sm_center_y - 30), dxfattribs={'layer': 'SAFE_STATE_MACH'})
    
    # 4. Right zone: NTC dual-channel sensor
    msp.add_lwpolyline([(320, 210), (380, 210), (380, 260), (320, 260), (320, 210)], dxfattribs={'layer': 'ELEC_SIG'})
    msp.add_text("NTC Dual-Channel\nTemperature Sensor", dxfattribs={'layer': 'TEXT', 'height': 3}).set_placement((325, 245))
    msp.add_text("Steinhart-Hart Formula:\n1/T = A + B*ln(R) + C*(ln(R))^3", dxfattribs={'layer': 'TEXT', 'height': 2}).set_placement((325, 220))

    # 5. Bottom zone: Derating curve graph
    msp.add_lwpolyline([(160, 50), (260, 50)], dxfattribs={'layer': 'SAFE_DEGRADE'}) # X axis
    msp.add_lwpolyline([(160, 50), (160, 110)], dxfattribs={'layer': 'SAFE_DEGRADE'}) # Y axis
    msp.add_text("60°C", dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((180, 45))
    msp.add_text("85°C", dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((240, 45))
    msp.add_text("0%", dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((150, 50))
    msp.add_text("100%", dxfattribs={'layer': 'TEXT', 'height': 2.5}).set_placement((145, 105))
    
    # Curve
    msp.add_lwpolyline([(160, 105), (180, 105), (240, 50), (260, 50)], dxfattribs={'layer': 'SAFE_DEGRADE'})
    msp.add_text("Derating Curve", dxfattribs={'layer': 'TEXT', 'height': 3}).set_placement((180, 115))

    # 6. Mandatory Annotations
    msp.add_text("≥3.5A → Emergency Shutdown (5ms)", dxfattribs={'layer': 'SAFE_OC', 'height': 3}).set_placement((20, 100))
    msp.add_text("≥8.0A → Short Circuit Lock", dxfattribs={'layer': 'SAFE_OC', 'height': 3}).set_placement((20, 90))
    msp.add_text("|ΔT| > 5.0°C → NTC_MISMATCH DTC", dxfattribs={'layer': 'SAFE_DEGRADE', 'height': 3}).set_placement((20, 80))
    msp.add_text("2ms(Sense) + 1ms(Diag) + 2ms(Cut) = 5ms << 100ms FTTI", dxfattribs={'layer': 'SAFE_FTTI', 'height': 3}).set_placement((20, 70))

    # Save
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    doc.saveas(output_path)
    print(f"DXF saved to {output_path}")

if __name__ == '__main__':
    # Determine the project root from script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    output_path = os.path.join(project_root, 'DATA', 'A3_LightingControl_Derating_Architecture.dxf')
    generate_lighting_derating_a3_dxf(output_path)
