name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Commitlint Dependencies
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v6
